### ISSUE TITLE
Resubmit bug

### ISSUE THREAD

**Issue by mooreryan** [mooreryan/iroki_web#4]
I got a completed job, then hit the back button. Changed the coloring options (unselect labels and exact) then resubmitted and got this `ActiveJob` error

```
[Worker(host:Ryans-MacBook-Pro.local pid:66999)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=8) FAILED (0 prior attempts) with TypeError: type mismatch: String given
```

Then rather than serving the error page, the worker keeps retrying with this error

```
[Worker(host:Ryans-MacBook-Pro.local pid:66999)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=8) FAILED (1 prior attempts) with ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find IrokiInput with 'id'=8
```

**Comment by mooreryan** [comment]
Got the error again...here are the controller params
![error](https://cloud.githubusercontent.com/assets/3172014/25734343/b462e82a-312f-11e7-8d5c-815df821e7f9.png)

**Comment by mooreryan** [comment]
Turns out that this is an error in the Iroki lib. Still, the Active Job workers should probably handle uncaught exceptions like these.

When there is a biom file and a color map file with regex matching...

```
mooreryan | fig_4 -> iroki -t -c fh_color_map.txt -i ln.txt -f samples.upgma.tre.txt -o TESTST -m 1 -x 100 -s 1
I, [2017-05-05T01:19:22.958789 #68555]  INFO -- : Args color_branches = false, color_taxa_names = true, exact = false, remove_bootstraps_below = nil, color_map_f = "fh_color_map.txt", biom_f = "ln.txt", single_color = true, name_map_f = nil, auto_color = nil, display_auto_color_options = false, newick_f = "samples.upgma.tre.txt", out_f = "TESTST", default_color = "black", min_lumin = 1, max_lumin = 100
/Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:49:in `=~': type mismatch: String given (TypeError)
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:49:in `block in add_color_to_leaf_branch'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:48:in `each'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:48:in `add_color_to_leaf_branch'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:395:in `block in main'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:392:in `map'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:392:in `main'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/exe/iroki:100:in `<top (required)>'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/iroki:23:in `load'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/iroki:23:in `<main>'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/ruby_executable_hooks:15:in `eval'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/ruby_executable_hooks:15:in `<main>'
```

If you remove the biom file, you get a non specific matching error, which is correct.

```
mooreryan | fig_4 -> iroki -t -c fh_color_map.txt -f samples.upgma.tre.txt -o TESTST -m 1 -x 100
I, [2017-05-05T01:26:16.220886 #69127]  INFO -- : Args color_branches = false, color_taxa_names = true, exact = false, remove_bootstraps_below = nil, color_map_f = "fh_color_map.txt", biom_f = nil, single_color = false, name_map_f = nil, auto_color = nil, display_auto_color_options = false, newick_f = "samples.upgma.tre.txt", out_f = "TESTST", default_color = "black", min_lumin = 1, max_lumin = 100
F, [2017-05-05T01:26:16.288904 #69127] FATAL -- : Non specific matching for f546
```

Also gets the error with no color map and just biom file....

```
mooreryan | fig_4 -> iroki -t -i ln.txt -f samples.upgma.tre.txt -o TESTST -m 1 -x 100 -s 1
I, [2017-05-05T01:28:28.183595 #69248]  INFO -- : Args color_branches = false, color_taxa_names = true, exact = false, remove_bootstraps_below = nil, color_map_f = nil, biom_f = "ln.txt", single_color = true, name_map_f = nil, auto_color = nil, display_auto_color_options = false, newick_f = "samples.upgma.tre.txt", out_f = "TESTST", default_color = "black", min_lumin = 1, max_lumin = 100
/Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:49:in `=~': type mismatch: String given (TypeError)
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:49:in `block in add_color_to_leaf_branch'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:48:in `each'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/utils/utils.rb:48:in `add_color_to_leaf_branch'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:395:in `block in main'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:392:in `map'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/lib/iroki/main/main.rb:392:in `main'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/gems/iroki-0.0.33/exe/iroki:100:in `<top (required)>'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/iroki:23:in `load'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/iroki:23:in `<main>'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/ruby_executable_hooks:15:in `eval'
	from /Users/moorer/.rvm/gems/ruby-2.3.1@DEFAULT/bin/ruby_executable_hooks:15:in `<main>'
```

When using exact matching all the above is fine.

**Comment by mooreryan** [comment]
This commit https://github.com/mooreryan/iroki/tree/69ecf8574db05ef90d58deeb389dfad0534cb6ca in the library repo takes care of this problem. It now renders the error page with a semi-helpful message.
